CREATE TABLE IF NOT EXISTS TABELA_MOVIMENTACOES_ESTOQUE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_produto BIGINT NOT NULL,
    tipo ENUM('ENTRADA', 'SAIDA') NOT NULL,
    quantidade DECIMAL(10,2) NOT NULL,
    motivo VARCHAR(255),
    id_usuario BIGINT,
    data_movimentacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_produto_mov FOREIGN KEY (id_produto) REFERENCES TABELA_PRODUTOS(id),
    CONSTRAINT fk_usuario_mov FOREIGN KEY (id_usuario) REFERENCES TABELA_USUARIOS(id)
);
